services:
  php:
    user: "${USER_ID}:${GROUP_ID}"
    image: php:8.2-cli
    ports:
      - 8000:80
      - 8000:8000
    working_dir: /app
    volumes:
      - .:/app
    command: php -S localhost:8000 kirby/router.php
  
  bun:
    user: "${USER_ID}:${GROUP_ID}"
    image: oven/bun
    command: bun run dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
  
  composer:
    user: "${USER_ID}:${GROUP_ID}"
    image: composer:lts
    working_dir: /app
    volumes:
      - .:/app
    command: install --ignore-platform-reqs
    