services:
  php:
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      APP_ENV: dev
    working_dir: /app
    volumes:
      - .:/app
    command: php -d memory_limit=512M -S 0.0.0.0:8000 kirby/router.php
  
  bun:
    user: "${USER_ID}:${GROUP_ID}"
    image: oven/bun:slim
    command: bun run dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000